# Generated by Django 4.1.1 on 2022-10-12 05:42

import django.core.validators
from django.db import migrations, models
import practice_django_project.core.model_mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('author', models.CharField(max_length=100)),
                ('pages', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10000)])),
                ('is_finished', models.BooleanField()),
                ('is_to_read', models.BooleanField()),
                ('is_currently_read', models.BooleanField()),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            bases=(practice_django_project.core.model_mixins.StrFromFieldsMixin, models.Model),
        ),
    ]
