# Generated by Django 4.1.1 on 2022-10-12 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('NR', 'Not yet read'), ('CR', 'Currently reading'), ('TR', 'To read')], default='NR', max_length=20),
        ),
    ]
