# Generated by Django 4.1.1 on 2022-10-12 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('NR', 'Not yet read'), ('CR', 'Currently reading'), ('TR', 'To read'), ('FN', 'Finished')], default='NR', max_length=20),
        ),
    ]
