# Generated by Django 4.1.1 on 2022-10-12 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='is_currently_read',
        ),
        migrations.RemoveField(
            model_name='book',
            name='is_finished',
        ),
        migrations.RemoveField(
            model_name='book',
            name='is_to_read',
        ),
    ]
