# Generated by Django 4.1.1 on 2022-10-12 08:42

from django.db import migrations, models
import django.db.models.deletion
import practice_django_project.core.model_mixins


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_book_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='books.book')),
            ],
            options={
                'ordering': ('id',),
            },
            bases=(practice_django_project.core.model_mixins.StrFromFieldsMixin, models.Model),
        ),
    ]
